"""
Exports WIDE_EASTASIAN table keyed by supporting unicode version level.

This code generated by wcwidth/bin/update-tables.py on 2024-07-11 06:58:07 UTC.
"""
WIDE_EASTASIAN = {
    '15.1.0': (
        # Source: EastAsianWidth-15.1.0.txt
        # Date: 2023-07-28, 23:34:08 GMT
        #
        (0x002c4, 0x002c4,),  # Modifier Letter Up Arrowhead
        (0x002c7, 0x002c7,),  # Caron
        (0x002c9, 0x002cb,),  # Modifier Letter Macron  ..Modifier Letter Grave Ac
        (0x002cd, 0x002cd,),  # Modifier Letter Low Macron
        (0x002d0, 0x002d0,),  # Modifier Letter Triangular Colon
        (0x002d8, 0x002db,),  # Breve                   ..Ogonek
        (0x002dd, 0x002dd,),  # Double Acute Accent
        (0x002df, 0x002df,),  # Modifier Letter Cross Accent
        (0x00391, 0x003a1,),  # Greek Capital Letter Alp..Greek Capital Letter Rho
        (0x003a3, 0x003a9,),  # Greek Capital Letter Sig..Greek Capital Letter Ome
        (0x003b1, 0x003c1,),  # Greek Small Letter Alpha..Greek Small Letter Rho
        (0x003c3, 0x003c9,),  # Greek Small Letter Sigma..Greek Small Letter Omega
        (0x00401, 0x00401,),  # Cyrillic Capital Letter Io
        (0x00410, 0x0044f,),  # Cyrillic Capital Letter ..Cyrillic Small Letter Ya
        (0x00451, 0x00451,),  # Cyrillic Small Letter Io
        (0x01100, 0x0115f,),  # Hangul Choseong Kiyeok  ..Hangul Choseong Filler
        (0x02010, 0x02010,),  # Hyphen
        (0x02013, 0x02016,),  # En Dash                 ..Double Vertical Line
        (0x02018, 0x02019,),  # Left Single Quotation Ma..Right Single Quotation M
        (0x0201c, 0x0201d,),  # Left Double Quotation Ma..Right Double Quotation M
        (0x02020, 0x02022,),  # Dagger                  ..Bullet
        (0x02024, 0x02027,),  # One Dot Leader          ..Hyphenation Point
        (0x02030, 0x02030,),  # Per Mille Sign
        (0x02032, 0x02033,),  # Prime                   ..Double Prime
        (0x02035, 0x02035,),  # Reversed Prime
        (0x0203b, 0x0203b,),  # Reference Mark
        (0x0203e, 0x0203e,),  # Overline
        (0x02074, 0x02074,),  # Superscript Four
        (0x0207f, 0x0207f,),  # Superscript Latin Small Letter N
        (0x02081, 0x02084,),  # Subscript One           ..Subscript Four
        (0x020ac, 0x020ac,),  # Euro Sign
        (0x02103, 0x02103,),  # Degree Celsius
        (0x02105, 0x02105,),  # Care Of
        (0x02109, 0x02109,),  # Degree Fahrenheit
        (0x02113, 0x02113,),  # Script Small L
        (0x02116, 0x02116,),  # Numero Sign
        (0x02121, 0x02122,),  # Telephone Sign          ..Trade Mark Sign
        (0x02126, 0x02126,),  # Ohm Sign
        (0x0212b, 0x0212b,),  # Angstrom Sign
        (0x02153, 0x02154,),  # Vulgar Fraction One Thir..Vulgar Fraction Two Thir
        (0x0215b, 0x0215e,),  # Vulgar Fraction One Eigh..Vulgar Fraction Seven Ei
        (0x02160, 0x0216b,),  # Roman Numeral One       ..Roman Numeral Twelve
        (0x02170, 0x02179,),  # Small Roman Numeral One ..Small Roman Numeral Ten
        (0x02189, 0x02189,),  # Vulgar Fraction Zero Thirds
        (0x02190, 0x02199,),  # Leftwards Arrow         ..South West Arrow
        (0x021b8, 0x021b9,),  # North West Arrow To Long..Leftwards Arrow To Bar O
        (0x021d2, 0x021d2,),  # Rightwards Double Arrow
        (0x021d4, 0x021d4,),  # Left Right Double Arrow
        (0x021e7, 0x021e7,),  # Upwards White Arrow
        (0x02200, 0x02200,),  # For All
        (0x02202, 0x02203,),  # Partial Differential    ..There Exists
        (0x02207, 0x02208,),  # Nabla                   ..Element Of
        (0x0220b, 0x0220b,),  # Contains As Member
        (0x0220f, 0x0220f,),  # N-ary Product
        (0x02211, 0x02211,),  # N-ary Summation
        (0x02215, 0x02215,),  # Division Slash
        (0x0221a, 0x0221a,),  # Square Root
        (0x0221d, 0x02220,),  # Proportional To         ..Angle
        (0x02223, 0x02223,),  # Divides
        (0x02225, 0x02225,),  # Parallel To
        (0x02227, 0x0222c,),  # Logical And             ..Double Integral
        (0x0222e, 0x0222e,),  # Contour Integral
        (0x02234, 0x02237,),  # Therefore               ..Proportion
        (0x0223c, 0x0223d,),  # Tilde Operator          ..Reversed Tilde
        (0x02248, 0x02248,),  # Almost Equal To
        (0x0224c, 0x0224c,),  # All Equal To
        (0x02252, 0x02252,),  # Approximately Equal To Or The Image Of
        (0x02260, 0x02261,),  # Not Equal To            ..Identical To
        (0x02264, 0x02267,),  # Less-than Or Equal To   ..Greater-than Over Equal
        (0x0226a, 0x0226b,),  # Much Less-than          ..Much Greater-than
        (0x0226e, 0x0226f,),  # Not Less-than           ..Not Greater-than
        (0x02282, 0x02283,),  # Subset Of               ..Superset Of
        (0x02286, 0x02287,),  # Subset Of Or Equal To   ..Superset Of Or Equal To
        (0x02295, 0x02295,),  # Circled Plus
        (0x02299, 0x02299,),  # Circled Dot Operator
        (0x022a5, 0x022a5,),  # Up Tack
        (0x022bf, 0x022bf,),  # Right Triangle
        (0x02312, 0x02312,),  # Arc
        (0x0231a, 0x0231b,),  # Watch                   ..Hourglass
        (0x02329, 0x0232a,),  # Left-pointing Angle Brac..Right-pointing Angle Bra
        (0x023e9, 0x023ec,),  # Black Right-pointing Dou..Black Down-pointing Doub
        (0x023f0, 0x023f0,),  # Alarm Clock
        (0x023f3, 0x023f3,),  # Hourglass With Flowing Sand
        (0x023fb, 0x023fe,),  # Power Symbol            ..Power Sleep Symbol
        (0x02460, 0x024ff,),  # Circled Digit One       ..Negative Circled Digit Z
        (0x025b2, 0x025b3,),  # Black Up-pointing Triang..White Up-pointing Triang
        (0x025b6, 0x025b7,),  # Black Right-pointing Tri..White Right-pointing Tri
        (0x025bc, 0x025bd,),  # Black Down-pointing Tria..White Down-pointing Tria
        (0x025c0, 0x025c1,),  # Black Left-pointing Tria..White Left-pointing Tria
        (0x025c6, 0x025c8,),  # Black Diamond           ..White Diamond Containing
        (0x025cb, 0x025cb,),  # White Circle
        (0x025ce, 0x025d1,),  # Bullseye                ..Circle With Right Half B
        (0x025e2, 0x025e5,),  # Black Lower Right Triang..Black Upper Right Triang
        (0x025ef, 0x025ef,),  # Large Circle
        (0x025fd, 0x025fe,),  # White Medium Small Squar..Black Medium Small Squar
        (0x02605, 0x02606,),  # Black Star              ..White Star
        (0x02609, 0x02609,),  # Sun
        (0x0260e, 0x0260f,),  # Black Telephone         ..White Telephone
        (0x02614, 0x02615,),  # Umbrella With Rain Drops..Hot Beverage
        (0x0261c, 0x0261c,),  # White Left Pointing Index
        (0x0261e, 0x0261e,),  # White Right Pointing Index
        (0x02640, 0x02640,),  # Female Sign
        (0x02642, 0x02642,),  # Male Sign
        (0x02648, 0x02653,),  # Aries                   ..Pisces
        (0x02660, 0x02661,),  # Black Spade Suit        ..White Heart Suit
        (0x02663, 0x02665,),  # Black Club Suit         ..Black Heart Suit
        (0x02667, 0x0266a,),  # White Club Suit         ..Eighth Note
        (0x0266c, 0x0266d,),  # Beamed Sixteenth Notes  ..Music Flat Sign
        (0x0266f, 0x0266f,),  # Music Sharp Sign
        (0x0267f, 0x0267f,),  # Wheelchair Symbol
        (0x02693, 0x02693,),  # Anchor
        (0x0269e, 0x0269f,),  # Three Lines Converging R..Three Lines Converging L
        (0x026a1, 0x026a1,),  # High Voltage Sign
        (0x026aa, 0x026ab,),  # Medium White Circle     ..Medium Black Circle
        (0x026bd, 0x026bf,),  # Soccer Ball             ..Squared Key
        (0x026c4, 0x026e1,),  # Snowman Without Snow    ..Restricted Left Entry-2
        (0x026e3, 0x026e3,),  # Heavy Circle With Stroke And Two Dots Above
        (0x026e8, 0x026ff,),  # Black Cross On Shield   ..White Flag With Horizont
        (0x02705, 0x02705,),  # White Heavy Check Mark
        (0x0270a, 0x0270b,),  # Raised Fist             ..Raised Hand
        (0x02728, 0x02728,),  # Sparkles
        (0x0273d, 0x0273d,),  # Heavy Teardrop-spoked Asterisk
        (0x0274c, 0x0274c,),  # Cross Mark
        (0x0274e, 0x0274e,),  # Negative Squared Cross Mark
        (0x02753, 0x02755,),  # Black Question Mark Orna..White Exclamation Mark O
        (0x02757, 0x02757,),  # Heavy Exclamation Mark Symbol
        (0x02776, 0x0277f,),  # Dingbat Negative Circled..Dingbat Negative Circled
        (0x02795, 0x02797,),  # Heavy Plus Sign         ..Heavy Division Sign
        (0x027b0, 0x027b0,),  # Curly Loop
        (0x027bf, 0x027bf,),  # Double Curly Loop
        (0x02b1b, 0x02b1c,),  # Black Large Square      ..White Large Square
        (0x02b50, 0x02b50,),  # White Medium Star
        (0x02b55, 0x02b59,),  # Heavy Large Circle      ..Heavy Circled Saltire
        (0x02e80, 0x02e99,),  # Cjk Radical Repeat      ..Cjk Radical Rap
        (0x02e9b, 0x02ef3,),  # Cjk Radical Choke       ..Cjk Radical C-simplified
        (0x02f00, 0x02fd5,),  # Kangxi Radical One      ..Kangxi Radical Flute
        (0x02ff0, 0x03029,),  # Ideographic Description ..Hangzhou Numeral Nine
        (0x03030, 0x0303e,),  # Wavy Dash               ..Ideographic Variation In
        (0x03041, 0x03096,),  # Hiragana Letter Small A ..Hiragana Letter Small Ke
        (0x0309b, 0x030ff,),  # Katakana-hiragana Voiced..Katakana Digraph Koto
        (0x03105, 0x0312f,),  # Bopomofo Letter B       ..Bopomofo Letter Nn
        (0x03131, 0x0318e,),  # Hangul Letter Kiyeok    ..Hangul Letter Araeae
        (0x03190, 0x031e3,),  # Ideographic Annotation L..Cjk Stroke Q
        (0x031ef, 0x0321e,),  # (nil)                   ..Parenthesized Korean Cha
        (0x03220, 0x04dbf,),  # Parenthesized Ideograph ..Cjk Unified Ideograph-4d
        (0x04e00, 0x0a48c,),  # Cjk Unified Ideograph-4e..Yi Syllable Yyr
        (0x0a490, 0x0a4c6,),  # Yi Radical Qot          ..Yi Radical Ke
        (0x0a960, 0x0a97c,),  # Hangul Choseong Tikeut-m..Hangul Choseong Ssangyeo
        (0x0ac00, 0x0d7a3,),  # Hangul Syllable Ga      ..Hangul Syllable Hih
        (0x0e000, 0x0e09f,),  # (nil)
        (0x0e0a4, 0x0e0af,),  # (nil)
        (0x0e0c0, 0x0edff,),  # (nil)
        (0x0ee0c, 0x0fa6d,),  # (nil)                   ..Cjk Compatibility Ideogr
        (0x0fa70, 0x0fad9,),  # Cjk Compatibility Ideogr..Cjk Compatibility Ideogr
        (0x0fe10, 0x0fe19,),  # Presentation Form For Ve..Presentation Form For Ve
        (0x0fe30, 0x0fe52,),  # Presentation Form For Ve..Small Full Stop
        (0x0fe54, 0x0fe66,),  # Small Semicolon         ..Small Equals Sign
        (0x0fe68, 0x0fe6b,),  # Small Reverse Solidus   ..Small Commercial At
        (0x0ff01, 0x0ff60,),  # Fullwidth Exclamation Ma..Fullwidth Right White Pa
        (0x0ffe0, 0x0ffe6,),  # Fullwidth Cent Sign     ..Fullwidth Won Sign
        (0x0fffd, 0x0fffd,),  # Replacement Character
        (0x16fe0, 0x16fe3,),  # Tangut Iteration Mark   ..Old Chinese Iteration Ma
        (0x17000, 0x187f7,),  # (nil)
        (0x18800, 0x18cd5,),  # Tangut Component-001    ..Khitan Small Script Char
        (0x18d00, 0x18d08,),  # (nil)
        (0x1aff0, 0x1aff3,),  # Katakana Letter Minnan T..Katakana Letter Minnan T
        (0x1aff5, 0x1affb,),  # Katakana Letter Minnan T..Katakana Letter Minnan N
        (0x1affd, 0x1affe,),  # Katakana Letter Minnan N..Katakana Letter Minnan N
        (0x1b000, 0x1b122,),  # Katakana Letter Archaic ..Katakana Letter Archaic
        (0x1b132, 0x1b132,),  # Hiragana Letter Small Ko
        (0x1b150, 0x1b152,),  # Hiragana Letter Small Wi..Hiragana Letter Small Wo
        (0x1b155, 0x1b155,),  # Katakana Letter Small Ko
        (0x1b164, 0x1b167,),  # Katakana Letter Small Wi..Katakana Letter Small N
        (0x1b170, 0x1b2fb,),  # Nushu Character-1b170   ..Nushu Character-1b2fb
        (0x1f004, 0x1f004,),  # Mahjong Tile Red Dragon
        (0x1f0cf, 0x1f0cf,),  # Playing Card Black Joker
        (0x1f100, 0x1f10a,),  # Digit Zero Full Stop    ..Digit Nine Comma
        (0x1f110, 0x1f12d,),  # Parenthesized Latin Capi..Circled Cd
        (0x1f130, 0x1f169,),  # Squared Latin Capital Le..Negative Circled Latin C
        (0x1f170, 0x1f1ac,),  # Negative Squared Latin C..Squared Vod
        (0x1f200, 0x1f202,),  # Square Hiragana Hoka    ..Squared Katakana Sa
        (0x1f210, 0x1f23b,),  # Squared Cjk Unified Ideo..Squared Cjk Unified Ideo
        (0x1f240, 0x1f248,),  # Tortoise Shell Bracketed..Tortoise Shell Bracketed
        (0x1f250, 0x1f251,),  # Circled Ideograph Advant..Circled Ideograph Accept
        (0x1f260, 0x1f265,),  # Rounded Symbol For Fu   ..Rounded Symbol For Cai
        (0x1f300, 0x1f321,),  # Cyclone                 ..Thermometer
        (0x1f324, 0x1f393,),  # White Sun With Small Clo..Graduation Cap
        (0x1f396, 0x1f397,),  # Military Medal          ..Reminder Ribbon
        (0x1f399, 0x1f39b,),  # Studio Microphone       ..Control Knobs
        (0x1f39e, 0x1f3f0,),  # Film Frames             ..European Castle
        (0x1f3f3, 0x1f3f5,),  # Waving White Flag       ..Rosette
        (0x1f3f7, 0x1f3fa,),  # Label                   ..Amphora
        (0x1f400, 0x1f4fd,),  # Rat                     ..Film Projector
        (0x1f4ff, 0x1f53d,),  # Prayer Beads            ..Down-pointing Small Red
        (0x1f549, 0x1f54e,),  # Om Symbol               ..Menorah With Nine Branch
        (0x1f550, 0x1f567,),  # Clock Face One Oclock   ..Clock Face Twelve-thirty
        (0x1f56f, 0x1f570,),  # Candle                  ..Mantelpiece Clock
        (0x1f573, 0x1f57a,),  # Hole                    ..Man Dancing
        (0x1f587, 0x1f587,),  # Linked Paperclips
        (0x1f58a, 0x1f58d,),  # Lower Left Ballpoint Pen..Lower Left Crayon
        (0x1f590, 0x1f590,),  # Raised Hand With Fingers Splayed
        (0x1f595, 0x1f596,),  # Reversed Hand With Middl..Raised Hand With Part Be
        (0x1f5a4, 0x1f5a5,),  # Black Heart             ..Desktop Computer
        (0x1f5a8, 0x1f5a8,),  # Printer
        (0x1f5b1, 0x1f5b2,),  # Three Button Mouse      ..Trackball
        (0x1f5bc, 0x1f5bc,),  # Frame With Picture
        (0x1f5c2, 0x1f5c4,),  # Card Index Dividers     ..File Cabinet
        (0x1f5d1, 0x1f5d3,),  # Wastebasket             ..Spiral Calendar Pad
        (0x1f5dc, 0x1f5de,),  # Compression             ..Rolled-up Newspaper
        (0x1f5e1, 0x1f5e1,),  # Dagger Knife
        (0x1f5e3, 0x1f5e3,),  # Speaking Head In Silhouette
        (0x1f5e8, 0x1f5e8,),  # Left Speech Bubble
        (0x1f5ef, 0x1f5ef,),  # Right Anger Bubble
        (0x1f5f3, 0x1f5f3,),  # Ballot Box With Ballot
        (0x1f5fa, 0x1f64f,),  # World Map               ..Person With Folded Hands
        (0x1f680, 0x1f6c5,),  # Rocket                  ..Left Luggage
        (0x1f6cb, 0x1f6d2,),  # Couch And Lamp          ..Shopping Trolley
        (0x1f6d5, 0x1f6d7,),  # Hindu Temple            ..Elevator
        (0x1f6dc, 0x1f6e5,),  # Wireless                ..Motor Boat
        (0x1f6e9, 0x1f6e9,),  # Small Airplane
        (0x1f6eb, 0x1f6ec,),  # Airplane Departure      ..Airplane Arriving
        (0x1f6f0, 0x1f6f0,),  # Satellite
        (0x1f6f3, 0x1f6fc,),  # Passenger Ship          ..Roller Skate
        (0x1f7e0, 0x1f7eb,),  # Large Orange Circle     ..Large Brown Square
        (0x1f7f0, 0x1f7f0,),  # Heavy Equals Sign
        (0x1f90c, 0x1f93a,),  # Pinched Fingers         ..Fencer
        (0x1f93c, 0x1f945,),  # Wrestlers               ..Goal Net
        (0x1f947, 0x1f9ff,),  # First Place Medal       ..Nazar Amulet
        (0x1fa70, 0x1fa7c,),  # Ballet Shoes            ..Crutch
        (0x1fa80, 0x1fa88,),  # Yo-yo                   ..Flute
        (0x1fa90, 0x1fabd,),  # Ringed Planet           ..Wing
        (0x1fabf, 0x1fac5,),  # Goose                   ..Person With Crown
        (0x1face, 0x1fadb,),  # Moose                   ..Pea Pod
        (0x1fae0, 0x1fae8,),  # Melting Face            ..Shaking Face
        (0x1faf0, 0x1faf8,),  # Hand With Index Finger A..Rightwards Pushing Hand
        (0x20000, 0x2a6df,),  # Cjk Unified Ideograph-20..Cjk Unified Ideograph-2a
        (0x2a700, 0x2b739,),  # Cjk Unified Ideograph-2a..Cjk Unified Ideograph-2b
        (0x2b740, 0x2b81d,),  # Cjk Unified Ideograph-2b..Cjk Unified Ideograph-2b
        (0x2b820, 0x2cea1,),  # Cjk Unified Ideograph-2b..Cjk Unified Ideograph-2c
        (0x2ceb0, 0x2ebe0,),  # Cjk Unified Ideograph-2c..Cjk Unified Ideograph-2e
        (0x2ebf0, 0x2ee5d,),  # (nil)
        (0x2f800, 0x2fa1d,),  # Cjk Compatibility Ideogr..Cjk Compatibility Ideogr
        (0x30000, 0x3134a,),  # Cjk Unified Ideograph-30..Cjk Unified Ideograph-31
        (0x31350, 0x323af,),  # Cjk Unified Ideograph-31..Cjk Unified Ideograph-32
        (0xf0000, 0xffffd,),  # (nil)
    ),
}
