"""
Exports function list_versions() for unicode version level support.

This code generated by /tmp/sandbox/python-wcwidth/bin/update-tables.py on 2022-01-13 04:24:29.592119.
"""


def list_versions():
    """
    Return Unicode version levels supported by this module release.

    Any of the version strings returned may be used as keyword argument
    ``unicode_version`` to the ``wcwidth()`` family of functions.

    :returns: Supported Unicode version numbers in ascending sorted order.
    :rtype: list[str]
    """
    return (
        "14.0.0",
    )
