"""
Exports function list_versions() for unicode version level support.

This code generated by wcwidth/bin/update-tables.py on 2023-10-21 01:45:51 UTC.
"""


def list_versions():
    """
    Return Unicode version levels supported by this module release.

    Any of the version strings returned may be used as keyword argument
    ``unicode_version`` to the ``wcwidth()`` family of functions.

    :returns: Supported Unicode version numbers in ascending sorted order.
    :rtype: list[str]
    """
    return (
        "15.1.0",
    )
